dist: precise

language: php
node_js: "0.10"

cache:
  directories:
    - node_modules
    - vendor

php:
  - '7.2'
  - '7.1'

install:
  - yarn install
  - composer install
  - cp .env.example .env
  - php artisan key:generate
  - yarn run dev

script:
  - ./vendor/bin/phpunit

notifications:
  email:
    on_success: never
    on_failure: never